# Build a model that predicts whether a website is a Phishing website.


## Importing the libraries

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Data Preprocessing

In [3]:
dataset = pd.read_csv('Phishing Data.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[ 1  1  0 ...  0  1  1]
 [ 0  1  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  1]
 ...
 [ 0 -1  0 ...  0  0  0]
 [ 0 -1  0 ...  0  0  0]
 [ 0 -1  0 ...  0  0  0]]


In [5]:
print(y)

[1 1 1 ... 0 1 0]


* So the input having 30 coulumns as input and 1 coulmns as output.
* The techiques, i think, to get better result is ANN - Artifical Nueral Networks and SVM.
* Here we'll see SVM

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature scaling

In [7]:
#is required for all deep learning models

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
print(X_train)

[[-0.36777726 -0.46472808 -0.38103741 ...  2.57145933 -0.60327525
  -0.46567429]
 [ 2.71903703 -0.46472808  2.62441426 ... -0.38888424  1.14943568
   2.14742371]
 [-0.36777726 -0.46472808 -0.38103741 ... -0.38888424  1.14943568
  -0.46567429]
 ...
 [-0.36777726  2.19240717 -0.38103741 ... -0.38888424  1.14943568
  -0.46567429]
 [-0.36777726 -0.46472808 -0.38103741 ...  2.57145933  1.14943568
  -0.46567429]
 [-0.36777726 -0.46472808 -0.38103741 ... -0.38888424 -0.60327525
  -0.46567429]]


## Training the Kernel SVM model on the Training set

In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the result of a single observation

In [11]:
print(classifier.predict(sc.transform([[0,1,0,0,0,1,-1,1,-1,0,0,0,1,1,-1,1,1,1,0,0,0,0,0,1,1,1,-1,1,1,1]])) > 0.5)

[False]


Therefore, our model predict that a website is not a Phishing website!


## Predicting the Test set results

In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc = accuracy_score(y_test, y_pred)
print(acc)

[[255  12]
 [ 13 212]]
0.9491869918699187


In [16]:
print('% Accuracy of the model is ',acc*100)

% Accuracy of the model is  94.91869918699187
