# Build a model that predicts whether a website is a Phishing website.


## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

In [2]:
dataset = pd.read_csv('Phishing Data.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[ 1  1  0 ...  0  1  1]
 [ 0  1  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  1]
 ...
 [ 0 -1  0 ...  0  0  0]
 [ 0 -1  0 ...  0  0  0]
 [ 0 -1  0 ...  0  0  0]]


In [4]:
print(y)

[1 1 1 ... 0 1 0]


* So the input having 30 coulumns as input and 1 coulmns as output.
* The techiques, i think, to get better result is ANN - Artifical Nueral Networks.

## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature scaling

In [6]:
#is required for all deep learning models

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(X_train)

[[-0.36777726 -0.46472808 -0.38103741 ...  2.57145933 -0.60327525
  -0.46567429]
 [ 2.71903703 -0.46472808  2.62441426 ... -0.38888424  1.14943568
   2.14742371]
 [-0.36777726 -0.46472808 -0.38103741 ... -0.38888424  1.14943568
  -0.46567429]
 ...
 [-0.36777726  2.19240717 -0.38103741 ... -0.38888424  1.14943568
  -0.46567429]
 [-0.36777726 -0.46472808 -0.38103741 ...  2.57145933  1.14943568
  -0.46567429]
 [-0.36777726 -0.46472808 -0.38103741 ... -0.38888424 -0.60327525
  -0.46567429]]


## Building the ANN

In [8]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [9]:
# Adding the input layer and the first hidden layer# 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [10]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

In [12]:
# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
#  Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
62/62 [==============================] - 1s 2ms/step - loss: 0.7393 - accuracy: 0.5107
Epoch 2/100
62/62 [==============================] - 0s 2ms/step - loss: 0.6454 - accuracy: 0.6324
Epoch 3/100
62/62 [==============================] - 0s 2ms/step - loss: 0.5895 - accuracy: 0.7128
Epoch 4/100
62/62 [==============================] - 0s 2ms/step - loss: 0.5110 - accuracy: 0.8014
Epoch 5/100
62/62 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 0.8610
Epoch 6/100
62/62 [==============================] - 0s 2ms/step - loss: 0.3234 - accuracy: 0.8844
Epoch 7/100
62/62 [==============================] - 0s 2ms/step - loss: 0.2631 - accuracy: 0.8987
Epoch 8/100
62/62 [==============================] - 0s 2ms/step - loss: 0.2248 - accuracy: 0.9140
Epoch 9/100
62/62 [==============================] - 0s 2ms/step - loss: 0.1990 - accuracy: 0.9241
Epoch 10/100
62/62 [==============================] - 0s 2ms/step - loss: 0.1811 - accuracy: 0.9308
Epoch 11/

62/62 [==============================] - 0s 2ms/step - loss: 0.0799 - accuracy: 0.9695
Epoch 84/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0802 - accuracy: 0.9674
Epoch 85/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0793 - accuracy: 0.9689
Epoch 86/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0793 - accuracy: 0.9684
Epoch 87/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0787 - accuracy: 0.9695
Epoch 88/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0783 - accuracy: 0.9689
Epoch 89/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0781 - accuracy: 0.9664
Epoch 90/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0778 - accuracy: 0.9684
Epoch 91/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0779 - accuracy: 0.9689
Epoch 92/100
62/62 [==============================] - 0s 2ms/step - loss: 0.0772 - accuracy: 0.9689
Epoch 93/100


## Predicting the result of a single observation

In [14]:
print(ann.predict(sc.transform([[0,1,0,0,0,1,-1,1,-1,0,0,0,1,1,-1,1,1,1,0,0,0,0,0,1,1,1,-1,1,1,1]])) > 0.5)

[[False]]


Therefore, our model predict that a website is not a Phishing website!


## Predicting the Test set results

In [15]:

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc= accuracy_score(y_test, y_pred)
print (acc)

[[252  15]
 [ 13 212]]
0.943089430894309


In [17]:
print('% Accuracy of the model is ',acc*100)

% Accuracy of the model is  94.3089430894309
